demo/app/__init__.py
from flask import Flask
from config import config


# Create a flask app. Pass in a config
def create_app(config_name):
    app = Flask(__name__)

    # Pulls in all our variables set in the config and adds them to the flask app
    app.config.from_object(config[config_name]())
    config[config_name].init_app(app)

    # Adding blueprint from the main folder
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

demo/app/main/__init__.py
from flask import Blueprint

# Creates a blueprint for all our code under main
main = Blueprint('main', __name__)

from . import views

demo/app/main/views.py
import platform
import random
import string
import os
from flask import render_template, request, jsonify
from . import main


# Generate Random String
def get_random_string():
    # Grab the list of all ascii_letters + all digits
    letters_and_numbers = string.ascii_letters + string.digits

    # Using a random length between 5 and 15, generate a string of that length
    # The string will randomly choose from  all ascii_letters and all digits
    # Then join the string together
    random_string = ''.join(random.choice(letters_and_numbers) for _ in range(random.randint(5, 15)))

    return random_string


# Our route for displaying the bootstrap template
@main.route('/', methods=['GET', 'POST'])
def index():
    # Check if get got a POST request meaning someone click on a button
    if request.method == "POST":
        # Check if the button that was pressed was the "random-button"
        if request.form.get("random-button"):
            # Grab the name text string and then render the index.html page
            return render_template("index.html", random_text=get_random_string(), arch=str(platform.machine())), 200

    # If the request was a not a POST request then render the template with the default message
    return render_template("index.html", random_text="This text will change.... hit the button!",
                           arch=str(platform.machine())), 200


# Our route for display build info
@main.route('/build', methods=['GET'])
def build():
    # JSON blob
    build_object = {
        "VERSION": os.getenv('VERSION'),
        "CIRCLE_BUILD_URL": os.getenv('CIRCLE_BUILD_URL'),
        "CIRCLE_SHA1": os.getenv('CIRCLE_SHA1'),
        "CIRCLE_USERNAME": os.getenv('CIRCLE_USERNAME'),
        "CIRCLE_BUILD_NUM": os.getenv('CIRCLE_BUILD_NUM'),
        "ARCH": str(platform.machine())
    }

    # Return and render JSON object
    return jsonify(build_object)

demo/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
{% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock title %}</title>

  <!-- Custom fonts for this theme -->
  {% block fonts %}
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  {% endblock fonts %}

  <!-- Theme CSS -->
  {% block theme %}
  <link href="{{ url_for('static', filename='css/freelancer.min.css') }}" rel="stylesheet">
  {% endblock theme %}

{% endblock head %}
</head>


<body id="page-top">
{% block body %}
{% endblock body %}
</body>

</html>

demo/app/templates/index.html
{% extends "main.html" %}

{% block title %}Jim Crowley - Demo{% endblock title %}

{% block nav_name %}CircleCI Demo - Boot Camp {% endblock nav_name %}

{% block masthead_name %} {{ random_text }} {% endblock masthead_name %}
{% block masthead_sub %}Multi-Arch Builds are Awesome! Currently running on {{ arch }}!{% endblock masthead_sub %}
{% block masthead %}
    {{ super() }}
{% endblock masthead %}

demo/app/templates/layout.html
{% extends "base.html" %}

{% block body %}
  {% block nav %}
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">{% block nav_name %}Start Bootstrap{% endblock nav_name %}</a>
      <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% block nav_options %}
          {% endblock nav_options %}
        </ul>
      </div>
    </div>
  </nav>
  {% endblock nav %}

  {% block content %}
  {% endblock content %}

  {% block footer %}
  <!-- Footer -->
  <footer class="footer text-center">
    <div class="container">
      <div class="row">

        <!-- Footer Location -->
        <div class="col-lg-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4">Location</h4>
          <p class="lead mb-0">2215 John Daniel Drive
            <br>Clark, MO 65243</p>
        </div>

        <!-- Footer Social Icons -->
        <div class="col-lg-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4">Around the Web</h4>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-facebook-f"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-twitter"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-linkedin-in"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-dribbble"></i>
          </a>
        </div>

        <!-- Footer About Text -->
        <div class="col-lg-4">
          <h4 class="text-uppercase mb-4">About Freelancer</h4>
          <p class="lead mb-0">Freelance is a free to use, MIT licensed Bootstrap theme created by
            <a href="http://startbootstrap.com">Start Bootstrap</a>.</p>
        </div>

      </div>
    </div>
  </footer>

  <!-- Copyright Section -->
  <section class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Copyright &copy; Your Website 2019 | <a href="{{ url_for('main.build') }}">Build Info</a> </small>
    </div>
  </section>
  {% endblock footer %}


  {% block scripts %}
  <!-- Bootstrap core JavaScript -->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Plugin JavaScript -->
  <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Contact Form JavaScript -->
  <script src="{{ url_for('static', filename='js/jqBootstrapValidation.js') }}"></script>
  <script src="{{ url_for('static', filename='js/contact_me.js') }}"></script>

  <!-- Custom scripts for this template -->
  <script src="{{ url_for('static', filename='js/freelancer.min.js') }}"></script>
  {% endblock scripts %}

{% endblock body %}